### ISSUE TITLE
Using this block for over wifi streaming

### ISSUE THREAD

**Issue by kino-dome** [eighteight/Cinder-VideoStream#4]
Hi @eighteight ,

I just wanted to ask if you ever tried this block for over-wifi streaming? And if yes, how was the performance/delay? I have a project coming up in which I'll need to capture  Raspberry Pi cam and stream it over wifi. There's already a module called motion that uses mjpeg encoding to stream but to be honest I'd rather stay in Cinder's realm. I reckon your block does mjpeg too, right? I'm kind of a noob on Linux and raspberry so I'd appreciate a familiar face like libcinder's in the arsenal, so it'd be great if your block can help me with my project. Cheers!

**Comment by gusev-genotek** [comment]
@kino-dome yes, i tested it over wifi. Of course your particular wifi bandwidth can be a limiting factor, but one can cope with that by controlling the jpg compression [ratio](https://github.com/eighteight/Cinder-VideoStream/blob/a7f5863b5e25b42b08d5a65d5e70cfcbf6c1e374/samples/CinderVideoStreamServer/src/CinderVideoStreamServerApp.cpp#L101). This block can do a jpg [compression](https://github.com/eighteight/Cinder-VideoStream/blob/a7f5863b5e25b42b08d5a65d5e70cfcbf6c1e374/samples/CinderVideoStreamServer/src/CinderVideoStreamServerApp.cpp#L38) of each frame.

**Comment by kino-dome** [comment]
Brilliant! Thanks a lot for pointing out the parameters and the work for this block.

**Comment by gusev-genotek** [comment]
@kino-dome please share your experience with your setup here for future users.

**Comment by kino-dome** [comment]
Sure @eighteight , will do that definitely.
