### ISSUE TITLE
VLC as client

### ISSUE THREAD

**Issue by kino-dome** [eighteight/Cinder-VideoStream#5]
Hello again,

I managed to run the server and client on the same machine and it works great. I tried using VLC as the client, but it doesn't seem to recognize the stream. Sorry if it's a silly question, but does this block follow a custom protocol or the general Video Over IP Stream protocol?

**Comment by gusev-genotek** [comment]
I only tested it with both client and server provided in this repo. They are based on my own protocol which may or may not conform to other known protocols –– anyway, I haven't tested this with other clients such as VLC.
